import firebase_admin
from firebase_admin import credentials, firestore

cred = credentials.Certificate('serviceAccountKey.json')
firebase_admin.initialize_app(cred)

db = firestore.client()

medicines_data = [
  {
    "brand_name": "Ace",
    "generic_name": "Paracetamol",
    "drug_class": "Analgesic & Antipyretic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Square Pharmaceuticals PLC",
    "price": 1.20,
    "packaging": ["50 x 10", "25 x 10"],
    "description": "Ace is a widely used pain reliever and fever reducer. It is highly effective for mild to moderate pain including headache, migraine, muscle ache, and toothache.",
    "offer": "Buy 2 boxes, get 5% off",
    "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Napa",
    "generic_name": "Paracetamol",
    "drug_class": "Analgesic & Antipyretic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Beximco Pharmaceuticals Ltd.",
    "price": 1.20,
    "packaging": ["50 x 10"],
    "description": "Napa provides fast and effective relief from fever and pain. It is gentle on the stomach and suitable for daily use under medical guidance.",
    "offer": "Free shipping on orders over ৳500",
    "image_url": "https://images.unsplash.com/photo-1550572017-cedce486bbaf?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Reset",
    "generic_name": "Paracetamol",
    "drug_class": "Analgesic & Antipyretic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Incepta Pharmaceuticals Ltd.",
    "price": 1.20,
    "packaging": ["20 x 10"],
    "description": "Reset is an antipyretic agent that reduces fever and relieves minor aches. Ideal for post-vaccination fever and general body aches.",
    "offer": "10% off for first-time users",
    "image_url": "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Fast",
    "generic_name": "Paracetamol",
    "drug_class": "Analgesic & Antipyretic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Acme Laboratories Ltd.",
    "price": 1.20,
    "packaging": ["30 x 10"],
    "description": "Fast acts quickly to reduce high body temperatures and alleviate discomfort associated with cold and flu symptoms.",
    "offer": "No current offers",
    "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Xpa",
    "generic_name": "Paracetamol",
    "drug_class": "Analgesic & Antipyretic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Aristopharma Ltd.",
    "price": 1.20,
    "packaging": ["25 x 10"],
    "description": "Xpa effectively treats feverish conditions and provides symptomatic relief from mild to moderate pain.",
    "offer": "Save ৳20 on bulk purchase",
    "image_url": "https://images.unsplash.com/photo-1550572017-cedce486bbaf?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Seclo",
    "generic_name": "Omeprazole",
    "drug_class": "Proton Pump Inhibitor (PPI)",
    "form": "Capsule",
    "strength": "20 mg",
    "company": "Square Pharmaceuticals PLC",
    "price": 6.00,
    "packaging": ["10 x 10"],
    "description": "Seclo reduces the amount of acid produced in the stomach. It is used to treat gastroesophageal reflux disease (GERD) and other acid-related conditions.",
    "offer": "Buy 3 strips, save 10%",
    "image_url": "https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Losectil",
    "generic_name": "Omeprazole",
    "drug_class": "Proton Pump Inhibitor (PPI)",
    "form": "Capsule",
    "strength": "20 mg",
    "company": "Eskayef Pharmaceuticals Ltd.",
    "price": 5.50,
    "packaging": ["14 x 10"],
    "description": "Losectil is a trusted PPI that provides long-lasting relief from heartburn, acid indigestion, and sour stomach.",
    "offer": "Special discounted price",
    "image_url": "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Progut",
    "generic_name": "Omeprazole",
    "drug_class": "Proton Pump Inhibitor (PPI)",
    "form": "Capsule",
    "strength": "20 mg",
    "company": "Renata Limited",
    "price": 5.00,
    "packaging": ["10 x 10"],
    "description": "Progut effectively heals acid damage to the stomach and esophagus, prevents ulcers, and may help prevent cancer of the esophagus.",
    "offer": "No current offers",
    "image_url": "https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Ometec",
    "generic_name": "Omeprazole",
    "drug_class": "Proton Pump Inhibitor (PPI)",
    "form": "Capsule",
    "strength": "20 mg",
    "company": "Opsonin Pharma Ltd.",
    "price": 5.50,
    "packaging": ["12 x 10"],
    "description": "Ometec offers rapid relief from gastric acidity and helps in the eradication of H. pylori when used with antibiotics.",
    "offer": "Buy 5 strips, get 1 free",
    "image_url": "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Omep",
    "generic_name": "Omeprazole",
    "drug_class": "Proton Pump Inhibitor (PPI)",
    "form": "Capsule",
    "strength": "20 mg",
    "company": "Aristopharma Ltd.",
    "price": 6.00,
    "packaging": ["10 x 10"],
    "description": "Omep manages excess stomach acid production, ensuring comfortable digestion and preventing gastric discomfort.",
    "offer": "Free shipping on orders over ৳400",
    "image_url": "https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Fexo",
    "generic_name": "Fexofenadine",
    "drug_class": "Antihistamine",
    "form": "Tablet",
    "strength": "120 mg",
    "company": "Square Pharmaceuticals PLC",
    "price": 9.00,
    "packaging": ["5 x 10"],
    "description": "Fexo is a non-drowsy antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, and sneezing.",
    "offer": "15% off during allergy season",
    "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Fexofast",
    "generic_name": "Fexofenadine",
    "drug_class": "Antihistamine",
    "form": "Tablet",
    "strength": "120 mg",
    "company": "Beximco Pharmaceuticals Ltd.",
    "price": 8.50,
    "packaging": ["3 x 10"],
    "description": "Fexofast provides fast, 24-hour relief from indoor and outdoor allergies without causing drowsiness.",
    "offer": "Buy 2 get 10% off",
    "image_url": "https://images.unsplash.com/photo-1550572017-cedce486bbaf?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Telfast",
    "generic_name": "Fexofenadine",
    "drug_class": "Antihistamine",
    "form": "Tablet",
    "strength": "120 mg",
    "company": "Sanofi Bangladesh Ltd.",
    "price": 10.00,
    "packaging": ["5 x 10"],
    "description": "Telfast is a globally recognized premium brand for managing seasonal allergic rhinitis and chronic idiopathic urticaria.",
    "offer": "No current offers",
    "image_url": "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Dinofex",
    "generic_name": "Fexofenadine",
    "drug_class": "Antihistamine",
    "form": "Tablet",
    "strength": "120 mg",
    "company": "Incepta Pharmaceuticals Ltd.",
    "price": 8.00,
    "packaging": ["5 x 10"],
    "description": "Dinofex effectively blocks histamine in the body, preventing allergic reactions from dust, pet dander, and pollen.",
    "offer": "Save ৳50 on 2 boxes",
    "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Ritch",
    "generic_name": "Fexofenadine",
    "drug_class": "Antihistamine",
    "form": "Tablet",
    "strength": "120 mg",
    "company": "Opsonin Pharma Ltd.",
    "price": 8.50,
    "packaging": ["5 x 10"],
    "description": "Ritch offers reliable relief from hives and skin itching, ensuring you stay comfortable throughout the day.",
    "offer": "Free shipping",
    "image_url": "https://images.unsplash.com/photo-1550572017-cedce486bbaf?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Comet",
    "generic_name": "Metformin",
    "drug_class": "Anti-Diabetic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Square Pharmaceuticals PLC",
    "price": 4.00,
    "packaging": ["10 x 10"],
    "description": "Comet is a first-line medication for the treatment of type 2 diabetes. It helps control blood sugar levels effectively.",
    "offer": "Subscribe & Save 10% monthly",
    "image_url": "https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Metfo",
    "generic_name": "Metformin",
    "drug_class": "Anti-Diabetic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Beximco Pharmaceuticals Ltd.",
    "price": 3.50,
    "packaging": ["10 x 10"],
    "description": "Metfo improves insulin sensitivity and decreases glucose production in the liver, aiding in long-term diabetes management.",
    "offer": "Buy 2 boxes for ৳300",
    "image_url": "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Informin",
    "generic_name": "Metformin",
    "drug_class": "Anti-Diabetic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Incepta Pharmaceuticals Ltd.",
    "price": 3.50,
    "packaging": ["5 x 10"],
    "description": "Informin is an essential oral anti-diabetic drug that helps patients maintain stable glycemic control.",
    "offer": "No current offers",
    "image_url": "https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Normet",
    "generic_name": "Metformin",
    "drug_class": "Anti-Diabetic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Renata Limited",
    "price": 3.00,
    "packaging": ["10 x 10"],
    "description": "Normet provides a cost-effective solution for managing type 2 diabetes mellitus, especially in overweight patients.",
    "offer": "20% off on first order",
    "image_url": "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Nobesit",
    "generic_name": "Metformin",
    "drug_class": "Anti-Diabetic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Opsonin Pharma Ltd.",
    "price": 3.50,
    "packaging": ["10 x 10"],
    "description": "Nobesit is used alongside diet and exercise to improve blood sugar control in adults with type 2 diabetes.",
    "offer": "Buy 3 strips, get 1 free",
    "image_url": "https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Osartil",
    "generic_name": "Losartan Potassium",
    "drug_class": "Anti-Hypertensive",
    "form": "Tablet",
    "strength": "50 mg",
    "company": "Incepta Pharmaceuticals Ltd.",
    "price": 8.00,
    "packaging": ["5 x 10"],
    "description": "Osartil is used to treat high blood pressure (hypertension) and to help protect the kidneys from damage due to diabetes.",
    "offer": "Save 10% on 3 boxes",
    "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Angilock",
    "generic_name": "Losartan Potassium",
    "drug_class": "Anti-Hypertensive",
    "form": "Tablet",
    "strength": "50 mg",
    "company": "Square Pharmaceuticals PLC",
    "price": 9.00,
    "packaging": ["5 x 10"],
    "description": "Angilock relaxes blood vessels so that blood can flow more easily, lowering blood pressure and reducing the risk of strokes.",
    "offer": "Free delivery over ৳600",
    "image_url": "https://images.unsplash.com/photo-1550572017-cedce486bbaf?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Losartan",
    "generic_name": "Losartan Potassium",
    "drug_class": "Anti-Hypertensive",
    "form": "Tablet",
    "strength": "50 mg",
    "company": "Beximco Pharmaceuticals Ltd.",
    "price": 8.50,
    "packaging": ["5 x 10"],
    "description": "Losartan is an angiotensin II receptor blocker (ARB) that keeps blood vessels from narrowing, which lowers blood pressure.",
    "offer": "No current offers",
    "image_url": "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Prosan",
    "generic_name": "Losartan Potassium",
    "drug_class": "Anti-Hypertensive",
    "form": "Tablet",
    "strength": "50 mg",
    "company": "Renata Limited",
    "price": 7.50,
    "packaging": ["5 x 10"],
    "description": "Prosan is a reliable medication for long-term management of essential hypertension and diabetic nephropathy.",
    "offer": "Buy 2 get 5% off",
    "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Losa",
    "generic_name": "Losartan Potassium",
    "drug_class": "Anti-Hypertensive",
    "form": "Tablet",
    "strength": "50 mg",
    "company": "Opsonin Pharma Ltd.",
    "price": 8.00,
    "packaging": ["5 x 10"],
    "description": "Losa effectively controls high blood pressure, lowering the workload on the heart and improving cardiovascular health.",
    "offer": "Special discounted pack",
    "image_url": "https://images.unsplash.com/photo-1550572017-cedce486bbaf?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Zithrox",
    "generic_name": "Azithromycin",
    "drug_class": "Antibiotic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Square Pharmaceuticals PLC",
    "price": 35.00,
    "packaging": ["2 x 6"],
    "description": "Zithrox is a broad-spectrum macrolide antibiotic used to treat a wide variety of bacterial infections including respiratory and skin infections.",
    "offer": "Consult doctor before use",
    "image_url": "https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Azith",
    "generic_name": "Azithromycin",
    "drug_class": "Antibiotic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Beximco Pharmaceuticals Ltd.",
    "price": 35.00,
    "packaging": ["2 x 6"],
    "description": "Azith works by stopping the growth of bacteria. It is highly effective for treating tonsillitis, pneumonia, and certain sexually transmitted infections.",
    "offer": "No current offers",
    "image_url": "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Tridosil",
    "generic_name": "Azithromycin",
    "drug_class": "Antibiotic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Incepta Pharmaceuticals Ltd.",
    "price": 30.00,
    "packaging": ["3 x 4"],
    "description": "Tridosil provides a short-course therapy for bacterial infections, ensuring high patient compliance and fast recovery.",
    "offer": "Save ৳20 on full course",
    "image_url": "https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Odmon",
    "generic_name": "Azithromycin",
    "drug_class": "Antibiotic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Opsonin Pharma Ltd.",
    "price": 32.00,
    "packaging": ["3 x 4"],
    "description": "Odmon is prescribed for the treatment of mild to moderate infections caused by susceptible strains of designated microorganisms.",
    "offer": "No current offers",
    "image_url": "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=400&q=80"
  },
  {
    "brand_name": "Rozith",
    "generic_name": "Azithromycin",
    "drug_class": "Antibiotic",
    "form": "Tablet",
    "strength": "500 mg",
    "company": "Renata Limited",
    "price": 35.00,
    "packaging": ["2 x 6"],
    "description": "Rozith is an azalide antibiotic, effective against a variety of gram-positive and gram-negative bacteria.",
    "offer": "Free shipping on orders over ৳500",
    "image_url": "https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=400&q=80"
  }
]

for med in medicines_data:
    db.collection('medicines').document().set(med)

print("Data upload complete.")